### ISSUE TITLE
Provide Dockerfile

### ISSUE THREAD

**Issue by anhldbk** [ozuit/generators-web-project#2]
It's great if you can provide a Dockerfile image.

Here are what you should do:
- [Why Docker?](https://www.infoworld.com/article/3310941/why-you-should-use-docker-and-containers.html)
- Tutorial for Nodejs https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
- Make your own Dockerfile 
- Publish your image to DockerHub or [Github Packages](https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages)
- Update your docs

**Comment by ozuit** [comment]
Thank you for your contribution! I upgraded the project with Docker and updated Dockerfile in the repository. You also get more custom with Docker image in [here](https://hub.docker.com/repository/docker/duytan94/web-generators)
